name: ci-wf
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome steps
        run: echo "welcome to the GH Actions"
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Repository Information
        run: |
           echo "Repository name: ${{github.repository}}"
           echo "Type Of Event: ${{github.event_name}}"
           git -v
           git branch
           git log   